spring:
  profiles:
    active: dev-jdbc
  application:
    name: ${artifactId}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: 7004
  servlet:
    context-path: /${artifactId}

log:
  level: info